### ISSUE TITLE
Column within fluid Row for dataTableOutput("table")

### ISSUE THREAD

**Issue by adamrobinson361** [dfe-analytical-services/fe-outcome-success#4]
**Background**

dataTableOutput("table") currently is not in a column whereas the above dropdowns are. This means that they are not in line. 

**Recommendation**

Wrap this in a column(x, ) in the ui.R where x is the number of columns equal to those in the above.

**Comment by RupeshVekaria** [comment]
Good point - i have made this change in a branch

**Comment by adamrobinson361** [comment]
Great! I've reopened this as its not been pull requested into master yet. When you make a pull request make sure to put "to resolve #X" where X is the number of the issue. e.g. 4
