### ISSUE TITLE
Move chart to Interactive tab

### ISSUE THREAD

**Issue by adamrobinson361** [dfe-analytical-services/fe-outcome-success#7]
**Background**

The plot under the drop down is very confusing. I would expect to see this when i selected my provider, hit go and navigated to another tab.

**Recommendation**

I'd recommend moving this to the Interactive Tab

**Comment by RupeshVekaria** [comment]
We have built this app off the back of feedback on an Excel version from Ofsted and the plot on the summary page was a specific request from them so have not moved but will see what Ofsted think
