### ISSUE TITLE
Consider Slimming Down the Summary Page

### ISSUE THREAD

**Issue by adamrobinson361** [dfe-analytical-services/fe-outcome-success#8]
**Background**

As per title the summary page looks to have lots on it and it isnt clear straight away how this is informing users how to use the app. 

**Recommendation**

Consider slimming down if possible - might not be.

**Comment by RupeshVekaria** [comment]
Not really possible to slim down further - I had already done some trimming from the previous Excel based version - no one has really complained about the title or summary notes.
